# Generated by Django 5.0.6 on 2024-06-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leetai', '0002_answer_user_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
